[project]
name = "ml-ramverk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "numpy>=2.4.1",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0",
]
